# PATCH http://localhost:5000/orders/68d256a1-1f23-4be0-a2a8-c01613483824
# Content-Type: application/json

# {
#     "status":"Not Responding"
# }

GET https://procolis.com/api_v1/tarification 
token: e2b914224c00fe79c091141a3e4e6ce4322d57cddda165cc2119238db034d77d
key: 3b7238f231ce49a5a503a2b56395328a

# GET http://localhost:5000/orders

# GET http://localhost:5000/orders/68d256a1-1f23-4be0-a2a8-c01613483824

# POST http://localhost:5000/orders
# Content-Type: application/json

# {
#     "fullName" :"John Doe",
#     "phoneNumber":"0888888888",
#     "state":"Oran",
#     "StateNumber":31,
#     "city":"Es senia",
#     "productName":"Facial hair oil",
#     "price":2500,
#     "quantity":2,
#     "shippingPrice":800,
#     "shippingMethod":"Home",
#     "totalPrice":3200
# }