# POST http://localhost:5000/users/create
# Content-Type: application/json

# {
#     "username":"Sifeddine",
#     "password":"sigma",
# }

# POST http://localhost:5000/users/signup
# Content-Type: application/json

# {
#     "firstName":"Sifeddine",
#     "lastName":"Djedid",
#     "email":"chtiwaa@gmail.com",
#     "phoneNumber":"0778855354",
#     "password":"sifou2001"
# }

# POST http://localhost:5000/users/verify-user
# Content-Type: application/json

# {  
#     "email":"chtiwaa@gmail.com",
#     "otp":"012823"
# }

# POST http://localhost:5000/users/login
# Content-Type: application/json

# {  
#     "email":"chtiwaa@gmail.com",
#     "password":"sifou2001"
# }


# GET http://localhost:5000/users/validate

# GET http://localhost:5000/users/verify
