# POST http://localhost:5000/users/create
# Content-Type: application/json

# {
#     "username":"Sifeddine",
#     "password":"sigma",
# }

# POST http://localhost:5000/api/v1/users/signup
# Content-Type: application/json

# {
#     "firstName":"Sifeddine",
#     "lastName":"Djedid",
#     "email":"chtiwaa@gmail.com",
#     "phoneNumber":"0778855354",
#     "password":"sifou2001"
# }

# POST http://localhost:5000/api/v1/users/verify-otp
# Content-Type: application/json

# {  
#     "email":"chtiwaa@gmail.com",
#     "otp":"077800"
# }

# POST http://localhost:5000/api/v1/users/login
# Content-Type: application/json

# {  
#     "email":"chtiwaa@gmail.com",
#     "password":"sifou2001"
# }


GET http://localhost:5000/api/v1/shops


# GET http://localhost:5000/users/validate

# GET http://localhost:5000/users/verify
